# Generated by Django 5.1.6 on 2025-04-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='price',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
