# Generated by Django 5.1.6 on 2025-04-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoursesModel',
            new_name='CourseModel',
        ),
    ]
